// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYj_MyY6y1pmm1HhQBacaBkG2TGI_UxX0',
    appId: '1:803526502098:web:579f12dfe9322ce04c2f0b',
    messagingSenderId: '803526502098',
    projectId: 'femvitalis-6f5b6',
    authDomain: 'femvitalis-6f5b6.firebaseapp.com',
    storageBucket: 'femvitalis-6f5b6.firebasestorage.app',
    measurementId: 'G-9R9K0PLFRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9r2OOO5sJCeHEL1exuNWpl6GZdKioDV8',
    appId: '1:803526502098:android:ce67a23f6aa24f804c2f0b',
    messagingSenderId: '803526502098',
    projectId: 'femvitalis-6f5b6',
    storageBucket: 'femvitalis-6f5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQVjL346udXwDDGIDsNZMjXi0RYGeJT4',
    appId: '1:803526502098:ios:9ccffa62145a62e34c2f0b',
    messagingSenderId: '803526502098',
    projectId: 'femvitalis-6f5b6',
    storageBucket: 'femvitalis-6f5b6.firebasestorage.app',
    iosBundleId: 'com.example.femvitalis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQVjL346udXwDDGIDsNZMjXi0RYGeJT4',
    appId: '1:803526502098:ios:9ccffa62145a62e34c2f0b',
    messagingSenderId: '803526502098',
    projectId: 'femvitalis-6f5b6',
    storageBucket: 'femvitalis-6f5b6.firebasestorage.app',
    iosBundleId: 'com.example.femvitalis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYj_MyY6y1pmm1HhQBacaBkG2TGI_UxX0',
    appId: '1:803526502098:web:37ccf7986d7cf3d24c2f0b',
    messagingSenderId: '803526502098',
    projectId: 'femvitalis-6f5b6',
    authDomain: 'femvitalis-6f5b6.firebaseapp.com',
    storageBucket: 'femvitalis-6f5b6.firebasestorage.app',
    measurementId: 'G-DXM8LKL0ED',
  );
}
